source "https://rubygems.org"

gem "jekyll", "~> 3.9.0"
gem 'kramdown-parser-gfm', '~> 1.1.0'

gem 'jekyll-toc'

group :jekyll_plugins do
  gem 'jekyll-timeago', '~> 0.13.1'
end

install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :install_if => Gem.win_platform?